[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "^3.0.5" }

[dev-dependencies]
risc0-zkvm = { version = "^3.0.5" }
serde = { version = "1", features = ["derive"] }

[package.metadata.risc0]
methods = ["guest"]
